spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sar
    password:
  #  main:
  #    allow-bean-definition-overriding: true
  #  sql:
  #    init:
  #      mode=always:
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# ver1
setting:
  kafka-topic: my-topic
  kafka-group: my-group
  kafka-server: localhost:9092
  group: app-push-group
  commit: false
  earliest: earliest

#ver2
#  server.port=8081
#  server.servlet.context-path=/
#  server.servlet.encoding.charset=UTF-8
#  server.servlet.encoding.enabled=true
#  server.servlet.encoding.force=true

#setting:
#  bootstrapServers: 127.0.0.1:29092, 127.0.0.1:29093, 127.0.0.1:29094
#  ksb:
#    earliest: earliest
#    topic: app-push-topic
#    group: app-push-group
#    enable:
#      auto:
#        commit: false

logging:
  level:
    com.example.pro.controller: debug