spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sar
    password:
  #  main:
  #    allow-bean-definition-overriding: true
  #  sql:
  #    init:
  #      mode=always:
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
setting:
  kafka-topic: my-topic
  kafka-group: my-group
  kafka-server: localhost:9092'
  group: app-push-group
  commit: false
  earliest: earliest
logging:
  level:
    com.example.pro.controller: debug