spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sar
    password:
#  main:
#    allow-bean-definition-overriding: true
  sql:
    init:
      mode=always:
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379

# Actuator 관련 스크립트
management:
#  셧다운 사용 활성화
  endpoint:
    shutdown:
      enabled: true
#  헬스 디테일 활성화
    health:
      show-details: always
  #  엔드포인트 전체노출 활성화
  endpoints:
    web:
      exposure:
        include: "*"
#  info 정보 활성화
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: chhong
    projectName : myPro
# 로깅 레벨 수준설정
logging:
  level:
    com.example.pro.controller: debug
# 톰캣 메트릭 활성화
server:
  tomcat:
    mbeanregistry:
      enabled: true