spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sar
    password:
  #  main:
  #    allow-bean-definition-overriding: true
#  sql:
#    init:
#      mode=always:
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# 로깅 레벨 수준설정
logging:
  level:
    com.example.pro.controller: debug